package wetsch.jbcsserver.server.listeners;

/*
 * Last modified 6/14/2016
 */

/**
 * Event generated by the server when an event on the server occurs.
 * @author kevin
 *@version 1.0
 */
public class ServerEvent {
	private Object source = null;//The object that triggered the event.
	/**
	 * This constructor sets the source object and event that triggered this event.
	 * @param source The source object that triggered the event.
	 */
	public ServerEvent(Object source){
		this.source = source;
	}
	
	/**
	 * Returns the object that triggered the event.
	 * @return Object
	 */
	public Object getSource(){
		return this.source;
	}
}